### ISSUE TITLE
Error in plugin

### ISSUE THREAD

**Issue by SargonofAssyria** [vaneeten/domoticz-wudirect#10]
Got this error to day after installing the plugin.
`2022-04-07 14:11:32.135 Error: PWS: Call to function 'onMessage' failed, exception details:
2022-04-07 14:11:32.136 Error: PWS: Traceback (most recent call last):
2022-04-07 14:11:32.136 Error: PWS: File "/home/pi/domoticz/plugins/domoticz-wudirect/plugin.py", line 442, in onMessage
2022-04-07 14:11:32.136 Error: PWS: _plugin.onMessage(Connection, Data)
2022-04-07 14:11:32.136 Error: PWS: File "/home/pi/domoticz/plugins/domoticz-wudirect/plugin.py", line 376, in onMessage
2022-04-07 14:11:32.136 Error: PWS: value = self.Data[src]
2022-04-07 14:11:32.136 Error: PWS: KeyError: 'tempf'`

If you need debug output, please let me know.
19 devices are created, but not updated.
I am using:
Version: 2022.1 (build 14285)
Build Hash: 7cac83ba6
Compile Date: 2022-03-17 08:46:22
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

This the URL I get from the PWS:
`2022-04-07 17:20:31.864  PWS: URL CALLED: ID=a&PASSWORD=b&indoortempf=75.0&tempf=69.1&dewptf=41.7&windchillf=69.1&indoorhumidity=33&humidity=37&windspeedmph=0.0&windgustmph=0.0&winddir=193&absbaromin=29.038&baromin=29.988&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.000&solarradiation=0.24&UV=0&dateutc=2022-04-07%2015:20:30&softwaretype=EasyWeatherV1.6.4&action=updateraw&realtime=1&rtfreq=5
`

**Comment by SargonofAssyria** [comment]
It looks like the URL changed a bit with softwaretype=EasyWeatherV1.6.4
When I change line 305 in
`parsed = urlparse.urlparse("http://localhost/?"+Data["URL"])`
It looks like it is working...

**Comment by vaneeten** [comment]
Hi, I think the result of your change is more a happy accident. The info you sent points to a missing dictionary key, so I've added an extra check for that in version 0.2.5. Can't test it myself as I am not using Domoticz anymore, but it should work.

**Comment by SargonofAssyria** [comment]
Tnx, for trying to solve it, but the last commit did not solve the error.

**Comment by SargonofAssyria** [comment]
Hold on, it might be an other problem, this is the error.
`022-04-07 21:18:55.491 Error: PWS: Call to function 'onMessage' failed, exception details:
2022-04-07 21:18:55.494 Error: PWS: Traceback (most recent call last):
2022-04-07 21:18:55.494 Error: PWS: File "/home/pi/domoticz/plugins/domoticz-wudirect/plugin.py", line 443, in onMessage
2022-04-07 21:18:55.494 Error: PWS: global _plugin
2022-04-07 21:18:55.494 Error: PWS: File "/home/pi/domoticz/plugins/domoticz-wudirect/plugin.py", line 360, in onMessage
2022-04-07 21:18:55.494 Error: PWS: value = None
2022-04-07 21:18:55.494 Error: PWS: KeyError: 'humidity'`

**Comment by vaneeten** [comment]
I have added similar checks to all composite sensors. By the way - please verify your weather station is still sending Wunderground type data: my weather station had automatically switched to Ecowitt protocol after the 1.6.4. firmware update.
