### ISSUE TITLE
new error today

### ISSUE THREAD

**Issue by Eddie-BS** [vaneeten/domoticz-wudirect#9]
today I got some new error in my logging
````
2022-04-06 08:11:57.114 Error: WuDirect: Call to function 'onMessage' failed, exception details:
2022-04-06 08:11:57.115 Error: WuDirect: Traceback (most recent call last):
2022-04-06 08:11:57.115 Error: WuDirect: File "/home/pi/domoticz/plugins/domoticz-wudirect/plugin.py", line 434, in onMessage
2022-04-06 08:11:57.115 Error: WuDirect: _plugin.onMessage(Connection, Data)
2022-04-06 08:11:57.115 Error: WuDirect: File "/home/pi/domoticz/plugins/domoticz-wudirect/plugin.py", line 366, in onMessage
2022-04-06 08:11:57.115 Error: WuDirect: value = floatToString( parseFloatValue(self.Data[params[0]]) * 10.0 /3.6 )
2022-04-06 08:11:57.115 Error: WuDirect: TypeError: unsupported operand type(s) for *: 'NoneType' and 'float' 
````

**Comment by vaneeten** [comment]
Probably have some time on Friday to look at this!

**Comment by vaneeten** [comment]
Hi Eddie, I think I fixed it. Haven't run it myself, as I stopped using Domoticz...

**Comment by Eddie-BS** [comment]
tnx for your effort, too bad you stopped using domoticz, I thought you just had problems with your PWS ...
I will update the plugin as soon as the new version is visible in plugin-manager and let you know

**Comment by Eddie-BS** [comment]
still waiting for the plugin-manager to see the updated wudirect plugin

**Comment by Eddie-BS** [comment]
I manually updated the plugin, it works fine now.
btw, the rechargeable battery in my PWS went bad after more than 5 years in operation. The plugin went mad and gave me lots of errors (no battery empty signals ...) 
I changed the battery and all is back to normal.
thanks
